from freebox.auth import Auth, AuthorizationStatus
from freebox.client import Freebox
from freebox.lan import (
    Lan,
    LanConfig,
    LanHost,
    LanHostL2Ident,
    LanHostL3Connectivity,
    LanHostName,
    LanHostNetworkControl,
    LanHostType,
    LanInterface,
    Route,
)
from freebox.connection import (
    Connection,
    ConnectionConfiguration,
    ConnectionIpv6Configuration,
    ConnectionIpv6Delegation,
    ConnectionStatus,
    DDNSConfig,
    DDNSStatus,
    FtthStatus,
    LteAggregation,
    LteConfiguration,
    LteNetwork,
    LteRadio,
    LteRadioBand,
    LteSim,
    LteTunnel,
    LteTunnelDetails,
    XdslInfos,
    XdslStats,
    XdslStatus,
)
from freebox.discovery import DiscoveryInfo, discover, discover_http, discover_mdns, discover_remote_port
from freebox.events import EventStream, Notification
from freebox.exceptions import (
    AppsDenied,
    AuthenticationError,
    AuthorizationDenied,
    AuthorizationTimeout,
    DeniedFromExternalIP,
    FreeboxError,
    InsufficientRightsError,
    RateLimited,
    TokenRevoked,
)

__all__ = [
    # Client
    "Freebox",
    # Auth
    "Auth",
    "AuthorizationStatus",
    # LAN
    "Lan",
    "LanConfig",
    "LanHost",
    "LanHostL2Ident",
    "LanHostL3Connectivity",
    "LanHostName",
    "LanHostNetworkControl",
    "LanHostType",
    "LanInterface",
    "Route",
    # Discovery
    "DiscoveryInfo",
    "discover",
    "discover_http",
    "discover_mdns",
    "discover_remote_port",
    # Connection
    "Connection",
    "ConnectionStatus",
    "ConnectionConfiguration",
    "ConnectionIpv6Configuration",
    "ConnectionIpv6Delegation",
    "DDNSStatus",
    "DDNSConfig",
    "FtthStatus",
    "LteAggregation",
    "LteConfiguration",
    "LteNetwork",
    "LteRadio",
    "LteRadioBand",
    "LteSim",
    "LteTunnel",
    "LteTunnelDetails",
    "XdslInfos",
    "XdslStatus",
    "XdslStats",
    # Events
    "EventStream",
    "Notification",
    # Exceptions
    "FreeboxError",
    "AuthenticationError",
    "AuthorizationDenied",
    "AuthorizationTimeout",
    "TokenRevoked",
    "InsufficientRightsError",
    "DeniedFromExternalIP",
    "RateLimited",
    "AppsDenied",
]
