from freebox.auth import Auth, AuthorizationStatus
from freebox.client import Freebox
from freebox.dhcp import (
    Dhcp,
    DhcpConfig,
    DhcpDynamicLease,
    DhcpOption,
    DhcpStaticLease,
)
from freebox.dhcpv6 import Dhcpv6, Dhcpv6Config
from freebox.lan import (
    Lan,
    LanConfig,
    LanHost,
    LanHostL2Ident,
    LanHostL3Connectivity,
    LanHostName,
    LanHostNetworkControl,
    LanHostType,
    LanInterface,
    Route,
)
from freebox.connection import (
    Connection,
    ConnectionConfiguration,
    ConnectionIpv6Configuration,
    ConnectionIpv6Delegation,
    ConnectionStatus,
    DDNSConfig,
    DDNSStatus,
    FtthStatus,
    LteAggregation,
    LteConfiguration,
    LteNetwork,
    LteRadio,
    LteRadioBand,
    LteSim,
    LteTunnel,
    LteTunnelDetails,
    XdslInfos,
    XdslStats,
    XdslStatus,
)
from freebox.sfp import Sfp, SfpConfig, SfpStatus
from freebox.switch import Switch, SwitchPortConfig, SwitchPortMacEntry, SwitchPortStats, SwitchPortStatus
from freebox.wifi import (
    ExpectedPhy,
    Wifi,
    WifiAllowedComb,
    WifiAp,
    WifiApChannelSurveyData,
    WifiApConfig,
    WifiApHeConfig,
    WifiApHtConfig,
    WifiApStatus,
    WifiBss,
    WifiBssConfig,
    WifiBssStatus,
    WifiChannelUsage,
    WifiGlobalConfig,
    WifiGlobalState,
    WifiMacFilter,
    WifiNeighbor,
    WifiNeighborCap,
    WifiPlanning,
    WifiStation,
    WifiStationFlags,
    WifiStationStats,
    WifiSteeringConfig,
)
from freebox.vpn import (
    VPNClientConfig,
    VPNClientPPTPConfig,
    VPNClientStats,
    VPNClientStatus,
    VPNClientWireGuardConfig,
    VPNClientWireGuardIP,
    VPNConnection,
    VPNIPPool,
    VPNIPReservation,
    VPNIPSecAuthMode,
    VPNIPSecConfig,
    VPNOpenVpnConfig,
    VPNPPTPConfig,
    VPNServer,
    VPNServerConfig,
    VPNUser,
    VPNWireGuardServerConfig,
    VPNWireGuardUserConfig,
    VpnClient,
    VpnServer,
)
from freebox.notif import Notif, NotificationTarget
from freebox.rrd import Rrd, RRDDatabase, RRDResult, RRDSample
from freebox.system import (
    System,
    SystemConfig,
    SystemExpansion,
    SystemFan,
    SystemModelInfo,
    SystemSensor,
)
from freebox.update import Update, UpdateStatus, UpgradeState
from freebox.discovery import DiscoveryInfo, discover, discover_http, discover_mdns, discover_remote_port
from freebox.events import EventStream, Notification
from freebox.exceptions import (
    AppsDenied,
    AuthenticationError,
    AuthorizationDenied,
    AuthorizationTimeout,
    DeniedFromExternalIP,
    FreeboxError,
    InsufficientRightsError,
    RateLimited,
    TokenRevoked,
)

__all__ = [
    # Client
    "Freebox",
    # Auth
    "Auth",
    "AuthorizationStatus",
    # DHCP
    "Dhcp",
    "DhcpConfig",
    "DhcpDynamicLease",
    "DhcpOption",
    "DhcpStaticLease",
    # DHCPv6
    "Dhcpv6",
    "Dhcpv6Config",
    # LAN
    "Lan",
    "LanConfig",
    "LanHost",
    "LanHostL2Ident",
    "LanHostL3Connectivity",
    "LanHostName",
    "LanHostNetworkControl",
    "LanHostType",
    "LanInterface",
    "Route",
    # SFP
    "Sfp",
    "SfpConfig",
    "SfpStatus",
    # Switch
    "Switch",
    "SwitchPortConfig",
    "SwitchPortMacEntry",
    "SwitchPortStats",
    "SwitchPortStatus",
    # Wi-Fi
    "ExpectedPhy",
    "Wifi",
    "WifiAllowedComb",
    "WifiAp",
    "WifiApChannelSurveyData",
    "WifiApConfig",
    "WifiApHeConfig",
    "WifiApHtConfig",
    "WifiApStatus",
    "WifiBss",
    "WifiBssConfig",
    "WifiBssStatus",
    "WifiChannelUsage",
    "WifiGlobalConfig",
    "WifiGlobalState",
    "WifiMacFilter",
    "WifiNeighbor",
    "WifiNeighborCap",
    "WifiPlanning",
    "WifiStation",
    "WifiStationFlags",
    "WifiStationStats",
    "WifiSteeringConfig",
    # VPN
    "VpnServer",
    "VpnClient",
    "VPNServer",
    "VPNServerConfig",
    "VPNPPTPConfig",
    "VPNOpenVpnConfig",
    "VPNWireGuardServerConfig",
    "VPNIPSecAuthMode",
    "VPNIPSecConfig",
    "VPNUser",
    "VPNWireGuardUserConfig",
    "VPNIPPool",
    "VPNIPReservation",
    "VPNConnection",
    "VPNClientConfig",
    "VPNClientPPTPConfig",
    "VPNClientWireGuardConfig",
    "VPNClientWireGuardIP",
    "VPNClientStats",
    "VPNClientStatus",
    # Notifications
    "Notif",
    "NotificationTarget",
    # RRD
    "Rrd",
    "RRDDatabase",
    "RRDResult",
    "RRDSample",
    # System
    "System",
    "SystemConfig",
    "SystemExpansion",
    "SystemFan",
    "SystemModelInfo",
    "SystemSensor",
    # Update
    "Update",
    "UpdateStatus",
    "UpgradeState",
    # Discovery
    "DiscoveryInfo",
    "discover",
    "discover_http",
    "discover_mdns",
    "discover_remote_port",
    # Connection
    "Connection",
    "ConnectionStatus",
    "ConnectionConfiguration",
    "ConnectionIpv6Configuration",
    "ConnectionIpv6Delegation",
    "DDNSStatus",
    "DDNSConfig",
    "FtthStatus",
    "LteAggregation",
    "LteConfiguration",
    "LteNetwork",
    "LteRadio",
    "LteRadioBand",
    "LteSim",
    "LteTunnel",
    "LteTunnelDetails",
    "XdslInfos",
    "XdslStatus",
    "XdslStats",
    # Events
    "EventStream",
    "Notification",
    # Exceptions
    "FreeboxError",
    "AuthenticationError",
    "AuthorizationDenied",
    "AuthorizationTimeout",
    "TokenRevoked",
    "InsufficientRightsError",
    "DeniedFromExternalIP",
    "RateLimited",
    "AppsDenied",
]
